/**
 * The notification sounds, and how one gets played.
 *
 * The files in `public/sounds/` are generated by `scripts/make-sounds.mjs`
 * rather than downloaded, so the set here and the recipes there are two halves
 * of the same list: adding a sound means adding to both.
 *
 * This module deliberately knows nothing about settings. It is handed an id
 * and a volume, which keeps it free of the cycle it would otherwise make with
 * `storage.ts`, where the id is stored.
 */

import { getAudioContext } from "./audioContext";

export type NotificationSoundId = "chime" | "ping" | "pop" | "knock" | "glass" | "none";

export interface NotificationSoundInfo {
  id: NotificationSoundId;
  /** Served from `public/`, or null for the entry that plays nothing. */
  file: string | null;
}

/** In the order the settings list shows them, default first. */
export const NOTIFICATION_SOUNDS: readonly NotificationSoundInfo[] = [
  { id: "chime", file: "chime.wav" },
  { id: "ping", file: "ping.wav" },
  { id: "pop", file: "pop.wav" },
  { id: "knock", file: "knock.wav" },
  { id: "glass", file: "glass.wav" },
  { id: "none", file: null },
] as const;

export const DEFAULT_NOTIFICATION_SOUND: NotificationSoundId = "chime";

export function isNotificationSoundId(value: unknown): value is NotificationSoundId {
  return NOTIFICATION_SOUNDS.some((sound) => sound.id === value);
}

/**
 * Decoded sounds, kept for the life of the page.
 *
 * A notification sound is a few tens of kilobytes decoded and is played over
 * and over, so fetching and decoding it once is the difference between a
 * sound that lands with the message and one that lands after it.
 */
const decoded = new Map<NotificationSoundId, AudioBuffer>();
const decoding = new Map<NotificationSoundId, Promise<AudioBuffer | null>>();

function soundUrl(file: string): string {
  // BASE_URL rather than a bare "/sounds/…" so the client still finds them if
  // it is ever served from a sub-path.
  const base = import.meta.env.BASE_URL || "/";
  return `${base.endsWith("/") ? base : `${base}/`}sounds/${file}`;
}

async function load(id: NotificationSoundId): Promise<AudioBuffer | null> {
  const cached = decoded.get(id);
  if (cached) return cached;

  const inFlight = decoding.get(id);
  if (inFlight) return inFlight;

  const file = NOTIFICATION_SOUNDS.find((sound) => sound.id === id)?.file;
  const ctx = getAudioContext();
  if (!file || !ctx) return null;

  const request = (async () => {
    try {
      const response = await fetch(soundUrl(file));
      if (!response.ok) return null;
      const buffer = await ctx.decodeAudioData(await response.arrayBuffer());
      decoded.set(id, buffer);
      return buffer;
    } catch {
      // Offline, blocked, or an engine that will not decode it. A missing
      // sound is not worth failing a notification over.
      return null;
    } finally {
      decoding.delete(id);
    }
  })();

  decoding.set(id, request);
  return request;
}

/**
 * Warms the cache so the first notification is not the one that pays for the
 * fetch. Safe to call repeatedly and safe to ignore.
 */
export function preloadNotificationSound(id: NotificationSoundId): void {
  if (id === "none") return;
  void load(id);
}

/** Plays one sound at `volume` (0 to 1). Silent ids and failures do nothing. */
export async function playNotificationSound(
  id: NotificationSoundId,
  volume = 0.6,
): Promise<void> {
  if (id === "none" || volume <= 0) return;
  const ctx = getAudioContext();
  if (!ctx) return;

  const buffer = await load(id);
  if (!buffer) return;

  try {
    const source = ctx.createBufferSource();
    source.buffer = buffer;
    const gain = ctx.createGain();
    gain.gain.value = Math.min(1, Math.max(0, volume));
    source.connect(gain);
    gain.connect(ctx.destination);
    source.start();
  } catch {
    // The context was closed or the engine refused to start a source.
  }
}
