/**
 * Generates `src/lib/emoji-data.ts` from the official Unicode emoji list.
 *
 * The alternative to generating it is either committing an opaque blob nobody
 * can audit, or taking on a dependency several times the size of this whole
 * client. Deriving it from the source of truth keeps the data honest and makes
 * updating to a new Unicode release a one-line change.
 *
 *   node scripts/make-emoji.mjs
 *
 * The generated file is committed, so this is only run to bump the version.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const UNICODE_VERSION = "16.0";
const SOURCE = `https://unicode.org/Public/emoji/${UNICODE_VERSION}/emoji-test.txt`;

const OUTPUT = fileURLToPath(new URL("../src/lib/emoji-data.ts", import.meta.url));

/**
 * Unicode's own groups, renamed to what a person picking an emoji expects to
 * read, and ordered the way a picker is usually laid out. A group absent from
 * this map is dropped: "Component" holds bare skin-tone modifiers and hair
 * colours, which are pieces of other emoji rather than emoji anyone sends.
 */
const GROUPS = new Map([
  ["Smileys & Emotion", "Smileys"],
  ["People & Body", "People"],
  ["Animals & Nature", "Nature"],
  ["Food & Drink", "Food"],
  ["Travel & Places", "Travel"],
  ["Activities", "Activities"],
  ["Objects", "Objects"],
  ["Symbols", "Symbols"],
  ["Flags", "Flags"],
]);

/** Skin tone and hair modifiers, stripped so one entry stands for a family. */
const MODIFIER = /[\u{1F3FB}-\u{1F3FF}]|\u{1F9B0}|\u{1F9B1}|\u{1F9B2}|\u{1F9B3}/u;

/** The five Fitzpatrick modifiers, light to dark. */
const SKIN_TONES = ["\u{1F3FB}", "\u{1F3FC}", "\u{1F3FD}", "\u{1F3FE}", "\u{1F3FF}"];

/**
 * Applies a skin tone by inserting the modifier straight after the first
 * codepoint, which is the character the tone actually modifies.
 *
 * This is a rule rather than a lookup, so the generator checks it against
 * Unicode's own toned sequences below and only marks the emoji it reproduces
 * exactly. Guessing wrong would produce a sequence that renders as two
 * separate glyphs, which is worse than offering no tones at all.
 */
export function applyTone(emoji, tone) {
  const points = [...emoji];
  return [points[0], tone, ...points.slice(1)].join("");
}

async function main() {
  process.stdout.write(`fetching ${SOURCE}\n`);
  const response = await fetch(SOURCE);
  if (!response.ok) {
    throw new Error(`${SOURCE} returned ${response.status}`);
  }
  const text = await response.text();

  const groups = new Map([...GROUPS.values()].map((name) => [name, []]));
  /** Every fully-qualified toned sequence, so the tone rule can be checked. */
  const toned = new Set();
  let group = null;
  let skipped = 0;

  for (const line of text.split("\n")) {
    const groupHeader = line.match(/^# group: (.+)$/);
    if (groupHeader) {
      group = GROUPS.get(groupHeader[1].trim()) ?? null;
      continue;
    }
    if (group === null || line.startsWith("#") || line.trim() === "") continue;

    // codepoints ; status # emoji E<version> name
    const entry = line.match(/^[0-9A-F ]+;\s*(\S+)\s*#\s*(\S+)\s+E[\d.]+\s+(.+)$/);
    if (!entry) continue;

    const [, status, emoji, name] = entry;
    // A minimally-qualified or unqualified sequence renders inconsistently
    // across platforms; only the canonical form is worth offering.
    if (status !== "fully-qualified") continue;
    if (MODIFIER.test(emoji)) {
      toned.add(emoji);
      skipped += 1;
      continue;
    }

    groups.get(group).push([emoji, name.trim()]);
  }

  // An emoji gets a tone switch only when the insertion rule reproduces all
  // five of Unicode's own toned sequences for it, character for character.
  let tonable = 0;
  for (const list of groups.values()) {
    for (const item of list) {
      const supported = SKIN_TONES.every((tone) => toned.has(applyTone(item[0], tone)));
      if (supported) {
        item.push(1);
        tonable += 1;
      }
    }
  }

  const total = [...groups.values()].reduce((sum, list) => sum + list.length, 0);
  if (total < 1000) {
    throw new Error(`only parsed ${total} emoji, which means the format changed`);
  }

  const body = [...groups]
    .map(
      ([name, list]) =>
        `  {\n    name: ${JSON.stringify(name)},\n    emoji: [\n` +
        list
          .map(
            ([emoji, label, tones]) =>
              `      [${JSON.stringify(emoji)}, ${JSON.stringify(label)}${tones ? ", 1" : ""}],`,
          )
          .join("\n") +
        `\n    ],\n  },`,
    )
    .join("\n");

  const file = `/**
 * The emoji catalogue, generated by \`scripts/make-emoji.mjs\` from the Unicode
 * ${UNICODE_VERSION} emoji list. Do not edit by hand: run the script instead.
 *
 * Each entry is [character, name] with an optional 1 marking an emoji that
 * takes a skin tone. Toned variants are not listed: they are built by
 * inserting the modifier after the first codepoint, a rule the generator
 * verified against every toned sequence Unicode publishes.
 */

/** A catalogue entry: the character, its searchable name, and 1 if it tones. */
export type EmojiEntry = readonly [string, string] | readonly [string, string, 1];

export interface EmojiGroup {
  name: string;
  emoji: readonly EmojiEntry[];
}

export const UNICODE_EMOJI_VERSION = ${JSON.stringify(UNICODE_VERSION)};

export const EMOJI_GROUPS: readonly EmojiGroup[] = [
${body}
];
`;

  writeFileSync(OUTPUT, file, "utf8");
  process.stdout.write(
    `wrote ${OUTPUT}\n  ${total} emoji in ${groups.size} groups\n` +
      `  ${tonable} take a skin tone, ${skipped} toned variants folded away\n`,
  );
}

main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exit(1);
});
